instances:
  - name: es01
    dns:
      - es01.blockshain.com 
      - es01 
      - localhost
    ip:
      - 127.0.0.1

  - name: es02
    dns:
      - es02.blockshain.com 
      - es02
      - localhost
    ip:
      - 127.0.0.1

  - name: kibana
    dns:
      - kibana.blockshain.com 
      - kibana
      - localhost
    ip:
      - 127.0.0.1